name: Reload
version: ${project.version}
main: com.example.reload.ReloadPlugin
api-version: 1.21
commands:
  ro:
    description: 重载插件配置
    usage: /ro config
    permission: reload.command
    permission-message: "§c你没有权限使用此命令。"
